# Generated by Django 5.0.4 on 2024-04-05 20:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoObra',
            fields=[
                ('tipoObraId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTarea',
            fields=[
                ('tipoTareaId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('obraId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField()),
                ('fecha_actualizacion', models.DateField()),
                ('directorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
                ('tipoObraId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obra.tipoobra')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('tareaId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=50)),
                ('fecha_asignacion', models.DateField()),
                ('fecha_estimada', models.DateField()),
                ('fecha_registro', models.DateField()),
                ('fecha_actualizacion', models.DateField()),
                ('capatazId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
                ('obraId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obra.obra')),
                ('usuarios', models.ManyToManyField(related_name='usuarios', to='usuario.usuario')),
                ('tipoTareaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obra.tipotarea')),
            ],
        ),
    ]
