# Generated by Django 5.0.4 on 2024-04-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0002_tarea_status_alter_tarea_descripcion'),
        ('usuario', '0002_usuario_usuariodelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='usuarios',
            field=models.ManyToManyField(related_name='obras', to='usuario.usuario'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='usuarios',
            field=models.ManyToManyField(related_name='tareas', to='usuario.usuario'),
        ),
    ]
