# Generated by Django 5.0.4 on 2024-04-05 20:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('tipoIdentID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('tipoUsuarioId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('userioId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('noIdentificacion', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=50)),
                ('noCelular', models.CharField(max_length=20)),
                ('fecha_registro', models.DateField()),
                ('fecha_actualizacion', models.DateField()),
                ('tipoIdentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.tipoidentificacion')),
                ('tipoUsuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.tipousuario')),
            ],
        ),
    ]
