# Generated by Django 5.0.4 on 2024-04-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuariodelete',
            field=models.BooleanField(default=False),
        ),
    ]
