# Generated by Django 4.2.5 on 2024-04-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_usuariodelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_actualizacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
