# Generated by Django 4.2.5 on 2024-04-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='userioId',
            new_name='usuarioId',
        ),
    ]
