# Generated by Django 4.2.5 on 2024-04-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
